feature: Complete rehaul of neuftex. err: vim latex preview subrepo breaks things. Removed for now.

diff --git a/common/scripts/neuftex b/common/scripts/neuftex
--- a/common/scripts/neuftex
+++ b/common/scripts/neuftex
@@ -1,51 +1,122 @@
 #!/bin/bash
-# This script generates a new LaTeX document from a template.
-# You must supply a filename [name].tex
-# Options are [format]
-#             (1) article
-#             (2) paper
-#             (3) book
+
+#######################
+### Functions
+#######################
+
+CloneTemplates()
+{
+    # Check for tex-template in the script dir, and clone if necessary.
+    if [ ! -d $scriptdir/tex-template ]; then
+        echo "Cloning tex-template to" $templdir;
+        git clone git@bitbucket.org:racorbin/tex-template.git $templdir;
+        echo "tex-template repository created in" $templdir;
+    fi
+}
+
+BlankArgCheck()
+{
+    if [ "$1" == "" ]; then
+        echo "  No arguments given.";
+        echo "  Run this script again with the desired TeX document name as an argument."
+        Usage
+        echo "  See -h or --help for more details."
+        exit 1
+    fi
+}
+
+CopyTemplate()
+{
+    if [ -z "$filename" ]; then
+        echo "  No filename provided. Proper formatting is"
+        Usage
+        exit 1
+    fi
+
+    # Make the new document folder
+    here=$(pwd)
+    if [ ! -d $here/$filename ]; then
+        echo "  Creating a new $format directory at $here/$filename"
+        cp -r $templdir/$format $here/$filename
+        rm $here/$filename/*.pdf
+        mv $here/$filename/template.tex $here/$filename/$filename.tex
+    else
+        echo "  Directory $1 already exists! Exiting..."
+        exit
+    fi
+}
+
+Usage()
+{
+    echo "  > neuftex [-format] [-f name]"
+}
+
+Help()
+{
+    # display help message
+    echo
+    echo "  This script generates a new LaTeX document from a template."
+    echo "  You must supply a filename [name].tex"
+    echo "  The command format is: "
+    Usage
+    echo
+    echo "  [-format] options are:"
+    echo "              -a, -article  article"
+    echo "              -p, -paper    paper"
+    echo "              -b, -book     book"
+    echo "  The default template format is -a (article). "
+    echo
+    echo "  If no template directory is detected, it will be "
+    echo "  pulled from Bitbucket."
+    echo
+}
+
+#########################################
+### initialize
+#########################################
 
 # $# gives the number of arguments passed.
-
-
-scriptdir=$(echo $(dirname $0));                # Stores the dir containing this script
+scriptdir=$(echo $(dirname $0)); # Stores the dir containing this script
 templdir=$(echo "$scriptdir/tex-template");
+format="article" # default format.
 
-echo
+#########################################
+### main
+#########################################
 
-# Check for tex-template in the script dir, and clone if necessary.
-if [ ! -d $scriptdir/tex-template ]; then
-    echo "Cloning tex-template to" $templdir;
-    git clone git@bitbucket.org:racorbin/tex-template.git $templdir;
-    echo "tex-template repository created in" $templdir;
-    echo
-fi
+# check that there is at least one argument.
+BlankArgCheck $1
 
-# End script if no filename is given.
-case $# in
-    1) filename=$1;;
-    0) echo "No argument given.";
-       echo "Run this script again with the tex document name as an argument.";
-       echo "> $ neuftex <article type> <filename>"
-       echo "Article types are <book>, <paper>, <article>"
-       echo
-       exit;;
-esac
+while [ -n "$1" ]; do
+   case "$1" in
+      -h | --help)  # display Help
+                    Help
+                    exit;;
+      -f | --file)  shift
+                    filename=$1
+                    ;;
+      -a | --article) # article
+                    format="article";
+                    ;;
+      -p | --paper) # paper
+                    format="paper";
+                    ;;
+      -b | --book)  # book
+                    format="book";
+                    ;;
+     *) # bad option
+                    echo "  Error: Unknown option. The proper format is"
+                    Usage
+                    echo "  See -h for details."
+                    exit;;
+    esac
+    shift
+done
 
-# Make the new document folder
-here=$(pwd)
-if [ ! -d $here/$filename ]; then
-    echo "Creating a new directory at $here/$filename"
-    #echo "$templdir/book"
-    #echo "$here/$filename"
-    cp -r $templdir/book $here/$filename
-    rm $here/$filename/*.pdf
-    mv $here/$filename/template.tex $here/$filename/$filename.tex
-    echo
-else
-    echo "Directory already exists! Exiting..."
-    echo
-    exit
-fi
+####
 
+CloneTemplates
+
+CopyTemplate
+
+echo "  Done."
